services:
  task-ms:
    image: ghcr.io/juuwel/todo-app-task-ms:${GIT_TAG}
    build:
      context: .
      dockerfile: TaskMicroservice/Dockerfile
  
  user-ms:
    image: ghcr.io/juuwel/todo-app-user-ms:${GIT_TAG}
    build:
      context: .
      dockerfile: UserMicroservice/Dockerfile
      
  frontend:
    image: ghcr.io/juuwel/todo-app-todo-frontend:${GIT_TAG}
    build:
      context: ToDoFrontend
      dockerfile: Dockerfile