apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-db-volume-claim
  namespace: todo-app
  labels:
    app: task-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
