apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-microservice
  namespace: todo-app
  labels:
    app: task-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-microservice
  template:
    metadata:
      name: task-microservice
      labels:
        app: task-microservice
    spec:
      containers:
        - name: task-microservice
          image: ghcr.io/juuwel/todo-app-task-ms:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: Jwt__Key
              value: "e4c88641c473e0848a49431c9dafb5462efb3372dadd0403b3b60b8149cc9384"
            - name: Jwt__Issuer
              value: "https://to-do-or-not.todo"
            - name: Jwt__Audience
              value: "to-do-or-not.todo"
            - name: Jwt__ExpirationMinutes
              value: "1440"
            - name: AllowedOrigins
              value: "http://frontend:3000"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: task-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: task-db-secret
                  key: POSTGRES_DB
            - name: ConnectionStrings__DefaultConnection
              value: "Host=task-db;Port=5432;Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD);Database=$(POSTGRES_DB)"
          envFrom:
            - secretRef:
                name: task-db-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
