apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: todo-app
spec:
  selector:
    app: todo-frontend
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 80
