apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: todo-cert
  namespace: todo-app
spec:
  secretName: todo-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: todo.buchtik.top
  dnsNames:
    - todo.buchtik.top
