apiVersion: v1
kind: Service
metadata:
  name: user-microservice
  namespace: todo-app
spec:
  selector:
    app: user-microservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
