apiVersion: v1
kind: Service
metadata:
  name: user-microservice
  namespace: todo-app
spec:
  selector:
    app: user-microservice
  ports:
    - protocol: TCP
      port: 1001
      targetPort: 8080
  type: LoadBalancer
  